### ISSUE TITLE
BamQC Exception

### ISSUE THREAD

**Issue by FelixKrueger** [s-andrews/BamQC#25]
I just encountered this:

```
bamqc file.bam
...
Approx 100% complete for file.bam
Exception in thread "Thread-1" java.lang.ArrayIndexOutOfBoundsException: 0
        at uk.ac.babraham.BamQC.Modules.GenomeCoverage.processAnnotationSet(GenomeCoverage.java:160)
        at uk.ac.babraham.BamQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:265)
        at java.lang.Thread.run(Thread.java:745)
```
Thanks, Felix

**Comment by pdp10** [comment]
bam file used 8260 reference sequences and these were above the threshold: 
GenomeCoverage_plot_bins_all_chromosomes = 5000 
in BamQC/Configuration/limits.txt . 

A test was added so that plotBinsPerChromosome is never set to 0 in this situation.
Internal parameters for GenomeCoverage are now reported in log.debug().

**Comment by FelixKrueger** [comment]
Thanks Piero, the new version works just fine! Felix
